name:                lua-xls
version:             0.1.0.0
github:              "ziman/lua-xls"
license:             BSD3
author:              "Matus Tejiscak"
maintainer:          "ziman@functor.sk"
copyright:           "2020 Matus Tejiscak"
description:         Lua to spreadsheet compiler

dependencies:
- base >= 4.7 && < 5
- language-lua
- text

default-extensions:
- LambdaCase
- OverloadedStrings
- TypeApplications
- TypeOperators
- ScopedTypeVariables
- DeriveGeneric
- DeriveAnyClass
- DataKinds
- DerivingStrategies
- GeneralizedNewtypeDeriving
- ViewPatterns
- Strict
- FlexibleInstances
- FlexibleContexts
- GADTs
- TypeFamilies
- NamedFieldPuns
- RankNTypes
- MultiParamTypeClasses
- RecordWildCards
- MultiWayIf

source-dirs: src

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -Wall
- -Wextra
- -Werror

executables:
  lua-xls:
    main: Main.hs
