name:                ever-to-excel
version:             0.1.0.0
github:              "ziman/ever-to-excel"
license:             BSD3
author:              "Matus Tejiscak"
maintainer:          "ziman@functor.sk"
copyright:           "2020 Matus Tejiscak"
description:         Compiler to spreadsheets

dependencies:
- base >= 4.7 && < 5
- s-cargot
- optparse-applicative
- containers
- text
- parsec
- transformers

default-extensions:
- LambdaCase
- TypeApplications
- TypeOperators
- ScopedTypeVariables
- DeriveGeneric
- DeriveAnyClass
- DataKinds
- DerivingStrategies
- GeneralizedNewtypeDeriving
- ViewPatterns
- Strict
- FlexibleInstances
- FlexibleContexts
- GADTs
- TypeFamilies
- NamedFieldPuns
- RankNTypes
- MultiParamTypeClasses
- RecordWildCards
- MultiWayIf
#- OverloadedStrings

source-dirs: src

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -Wall
- -Wextra
- -Werror

executables:
  ever-to-excel:
    main: Main.hs
